# Generated by Django 5.1 on 2024-10-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('works_writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('WRITER', 'Writer'), ('READER', 'Reader')], default='READER', max_length=10)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='fa-user', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='works_writing.work')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='user_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReaderStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_read', models.PositiveIntegerField(default=0)),
                ('work_lists', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_stats', to='user_auth.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WriterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_written', models.PositiveIntegerField(default=0)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_stats', to='user_auth.profile')),
            ],
        ),
    ]
