LANGUAGE_ENGLISH = 'en'
LANGUAGE_FRENCH = 'fr'
LANGUAGE_SPANISH = 'es'
LANGUAGE_GERMAN = 'de'
LANGUAGE_UKRAINIAN = 'uk'

# Language Choices
LANGUAGE_CHOICES = [
    (LANGUAGE_ENGLISH, 'English'),
    (LANGUAGE_FRENCH, 'French'),
    (LANGUAGE_SPANISH, 'Spanish'),
    (LANGUAGE_GERMAN, 'German'),
    (LANGUAGE_UKRAINIAN, 'Ukrainian'),
]